export const AUTOMATION_DOMAIN_EVENTS = {
  WORKFLOW_CREATED: "automation.workflow.created",
  WORKFLOW_UPDATED: "automation.workflow.updated",
  WORKFLOW_DELETED: "automation.workflow.deleted",
  WORKFLOW_ENABLED: "automation.workflow.enabled",
  WORKFLOW_DISABLED: "automation.workflow.disabled",
  WORKFLOW_EXECUTION_STARTED: "automation.workflow.execution_started",
  WORKFLOW_EXECUTION_COMPLETED: "automation.workflow.execution_completed",
  WORKFLOW_EXECUTION_FAILED: "automation.workflow.execution_failed",
  WORKFLOW_EXECUTION_CANCELLED: "automation.workflow.execution_cancelled",
  WORKFLOW_STEP_STARTED: "automation.workflow.step_started",
  WORKFLOW_STEP_COMPLETED: "automation.workflow.step_completed",
  WORKFLOW_STEP_FAILED: "automation.workflow.step_failed",
  SCHEDULE_CREATED: "automation.schedule.created",
  SCHEDULE_UPDATED: "automation.schedule.updated",
  SCHEDULE_TRIGGERED: "automation.schedule.triggered",
  WEBHOOK_RECEIVED: "automation.webhook.received",
  WEBHOOK_PROCESSED: "automation.webhook.processed",
} as const;
