export const ANALYTICS_DOMAIN_EVENTS = {
  EVENT_INGESTED: "analytics.event.ingested",
  METRICS_REBUILT: "analytics.metrics.rebuilt",
  SNAPSHOT_CREATED: "analytics.snapshot.created",
  REPORT_GENERATED: "analytics.report.generated",
  REPORT_EXPORTED: "analytics.report.exported",
  DASHBOARD_REFRESHED: "analytics.dashboard.refreshed",
  CACHE_INVALIDATED: "analytics.cache.invalidated",
} as const;

export const ANALYTICS_SOURCE_EVENTS = [
  "order.created",
  "order.completed",
  "order.cancelled",
  "order.refunded",
  "order.shipped",
  "order.delivered",
  "order.returned",
  "catalog.product.created",
  "catalog.product.published",
  "catalog.product.updated",
  "catalog.product.deleted",
  "cms.content.published",
  "cms.content.updated",
  "finance.wallet_created",
  "finance.ledger_entry_created",
  "finance.profit_released",
  "finance.withdrawal_requested",
  "finance.withdrawal_approved",
  "finance.withdrawal_paid",
  "finance.settlement_completed",
  "finance.refund_processed",
  "courier.shipment_created",
  "courier.shipment_delivered",
  "courier.shipment_returned",
  "courier.tracking_updated",
  "inventory.stock_adjusted",
  "inventory.low_stock",
  "inventory.out_of_stock",
  "customer.created",
  "customer.updated",
  "identity.user_registered",
  "identity.profile_updated",
  "notification.sent",
  "notification.delivered",
  "notification.failed",
] as const;

export type AnalyticsSourceEvent = (typeof ANALYTICS_SOURCE_EVENTS)[number];
